HotelCostaRicaCore/HotelCostaRicaCore.Web/Models/Blog.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace HotelCostaRicaCore.Web.Models
{
    public class Blog
    {
        public int idBlog { get; set; }
        public string Imagen { get; set; }
        public DateTime Fecha { get; set; }
        public string Titulo { get; set; }
        public string Descripcion { get; set; }
        public string Usuario { get; set; }
        public int Vistas { get; set; }
        public string Tags { get; set; }
        public string ImageFullPath { get; set; }
        public object ImageBase64 { get; set; }

        public List<string> ListTags { 
            get {
                var arrayTags = new List<string>(Tags.Split(","));
                return arrayTags;
            }  
        }

    }
}

HotelCostaRicaCore/HotelCostaRicaCore.Web/Controllers/NosotrosController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using HotelCostaRicaCore.Web.Helpers;
using Microsoft.Extensions.Configuration;
using System.IO;
using Newtonsoft.Json;
using HotelCostaRicaCore.Web.Models;
using HotelCostaRicaCore.Web.Services;

namespace HotelCostaRicaCore.Web.Controllers
{
    

    public class NosotrosController : Controller
    {

        private readonly IEmailSender _emailSender;
        private readonly IApiService _apiService;

        IConfigurationRoot Configuration { get; } =
        ConfigurationHelper.GetConfiguration(Directory.GetCurrentDirectory());

        public NosotrosController(IEmailSender emailSender, IApiService apiService)
        {
            _emailSender = emailSender;
            this._apiService = apiService;
        }


        public async Task<IActionResult> Index()
        {
            //informacion de acceso ------------------------------
            var url = Constants.UrlAPI;
            var acceso = GetAccess.Instance(_apiService).GetToken();
            var _dataAccess = acceso.Result;

            //Informacion Blogs ------------------------------
            var responseBlog = await _apiService.GetBlogs(url, Constants.UrlAPP, "/api/Blog", _dataAccess.token_type, _dataAccess.access_token);
            if (responseBlog.Result != null && responseBlog.Result.blog.Count > 0)
            {
                ViewBag.BlogsFooter = responseBlog.Result.blog.Skip(0).Take(3);
            }

            return View();
        }
        public async Task<IActionResult> Blog(int id = 1)
        {
            //id es el numero de pagina
            int ArtculosPorPagina = 3;
            var reader = new StreamReader(Directory.GetCurrentDirectory() + "/appsettings.json");
            var appSettings = JsonConvert.DeserializeObject<AppSettingsProy>(reader.ReadToEnd());
            ViewBag.Articulos = appSettings.Articulos;
            ViewBag.MasArticulos = appSettings.Articulos.Take(3).ToList();


            ViewBag.totalblogs = 0;
            ViewBag.NumPagina = (id < 0 ) ? 1 : id;
            ViewBag.blogsPorPagina = ArtculosPorPagina;


            //informacion de acceso ------------------------------
            var url = Constants.UrlAPI;
            var acceso = GetAccess.Instance(_apiService).GetToken();
            var _dataAccess = acceso.Result;

            //Informacion Blogs ------------------------------
            var responseBlog = await _apiService.GetBlogs(url, Constants.UrlAPP, "/api/Blog", _dataAccess.token_type, _dataAccess.access_token);
            if (responseBlog.IsSuccess)
            {
                if (responseBlog.Result.blog.Count > 0)
                {
                    ViewBag.BlogsFooter = responseBlog.Result.blog.Skip(0).Take(3);
                    ViewBag.totalblogs = responseBlog.Result.blog.Count;
                    int skipBlog = (id * ArtculosPorPagina - ArtculosPorPagina);
                    ViewBag.Blogs = responseBlog.Result.blog.Skip(skipBlog).Take(ArtculosPorPagina);
                }
            }


            //--------------------------------------           
            ViewBag.ArticulosFooter = appSettings.Articulos.Take(3);

            return View();
        }

        public async Task<IActionResult> FAQ()
        {
            //informacion de acceso ------------------------------
            var url = Constants.UrlAPI;
            var acceso = GetAccess.Instance(_apiService).GetToken();
            var _dataAccess = acceso.Result;

            //Informacion Blogs ------------------------------
            var responseBlog = await _apiService.GetBlogs(url, Constants.UrlAPP, "/api/Blog", _dataAccess.token_type, _dataAccess.access_token);
            if (responseBlog.Result != null && responseBlog.Result.blog.Count > 0)
            {
                ViewBag.BlogsFooter = responseBlog.Result.blog.Skip(0).Take(3);
            }

            return View();
        }

        public async Task<IActionResult> Contacto()
        {
            //informacion de acceso ------------------------------
            var url = Constants.UrlAPI;
            var acceso = GetAccess.Instance(_apiService).GetToken();
            var _dataAccess = acceso.Result;

            //Informacion Blogs ------------------------------
            var responseBlog = await _apiService.GetBlogs(url, Constants.UrlAPP, "/api/Blog", _dataAccess.token_type, _dataAccess.access_token);
            if (responseBlog.Result != null && responseBlog.Result.blog.Count > 0)
            {
                ViewBag.BlogsFooter = responseBlog.Result.blog.Skip(0).Take(3);
            }

            return View();
        }

        public async Task<IActionResult> InternaBlog(int Id)
        {
 
            //informacion de acceso ------------------------------
            var url = Constants.UrlAPI;
            var acceso = GetAccess.Instance(_apiService).GetToken();
            var _dataAccess = acceso.Result;

            //Informacion Blogs ------------------------------
            var responseBlog = await _apiService.GetBlogs(url, Constants.UrlAPP, "/api/Blog", _dataAccess.token_type, _dataAccess.access_token);
            if (responseBlog.Result != null && responseBlog.Result.blog.Count > 0)
            {
                ViewBag.BlogsFooter = responseBlog.Result.blog.Skip(0).Take(3);
                ViewBag.MasArticulos = responseBlog.Result.blog.Skip(0).Take(3);
            }

            ViewBag.IdBlog = Id;
            ViewBag.totalComentariosInicial = 0;

            //Informacion Blog detalle ------------------------------
            var controller = "/api/Blog/Consultar?idBlog=" + Id;
            var responseBlogdetalle = await _apiService.GetBlogDetalle(url, Constants.UrlAPP, controller, _dataAccess.token_type, _dataAccess.access_token);
            if (responseBlogdetalle.IsSuccess)
            {
                ViewBag.blog = responseBlogdetalle.Result.blog;
                ViewBag.bloggers = responseBlogdetalle.Result.Bloggers;
                ViewBag.totalComentariosInicial = responseBlogdetalle.Result.Bloggers.Count;

                if (responseBlog.Result.blog.Count > 0)
                {
                    //int index = myList.FindIndex(a => a.Prop == oProp);
                    int indexBlog = responseBlog.Result.blog.FindIndex(x => x.idBlog == Id);
                                        
                    if(indexBlog == 0)
                    {
                        if(responseBlog.Result.blog.Count == 1)
                        {
                            ViewBag.BlogAnterior = responseBlog.Result.blog[0];
                        }
                        else
                        {
                            ViewBag.BlogAnterior = responseBlog.Result.blog[responseBlog.Result.blog.Count - 1];
                        }
                    }
                    else
                    {
                        ViewBag.BlogAnterior = responseBlog.Result.blog[indexBlog - 1];
                    }
                    

                    
                    if (indexBlog == (responseBlog.Result.blog.Count -1) )
                    {
                        ViewBag.BlogSiguiente = (responseBlog.Result.blog[0]);                        
                    }
                    else
                    {
                        ViewBag.BlogSiguiente = (responseBlog.Result.blog[indexBlog + 1]);
                    }

                }

            }

            return View();
        }

        public async Task<IActionResult> EnviarCorreo(MensajeContacto data)
        {
            
            string Mensaje = "<b>Nombre: </b>" + data.NomCliente + "<br>";
            Mensaje += "<b>Correo Electronico: </b>" + data.Email + "<br>";
            Mensaje += "<b>Mensaje: </b>" + data.Mensaje + "<br>";

            try
            {
                await _emailSender.SendEmailAsync("hulloa@sicsoftsa.com", "Asunto Correo", Mensaje, "mzamora@sicsoftsa.com").ConfigureAwait(false);                               
                return Json(new { IsSuccess = true });
            }
            catch (Exception ex)
            {
                var msg = ex.Message;
                return Json(new { IsSuccess = false });
            }

            return Json(new { IsSuccess = true });
        }


        [HttpPost]
        public async Task<IActionResult> GuardarComentario(RequestComentarioBlog data)
        {
            //informacion de acceso ------------------------------
            var url = Constants.UrlAPI;
            var acceso = GetAccess.Instance(_apiService).GetToken();
            var _dataAccess = acceso.Result;


            //Guardar comentario ------------------------------
            var responseGuardarComentarioBlog = await _apiService.PostGuardarComentarioBlog(url, Constants.UrlAPP, "/api/Blog/InsertarComentario", _dataAccess.token_type, _dataAccess.access_token, data);
            if(responseGuardarComentarioBlog.IsSuccess == true)
            {
                return Json(new { IsSuccess = true, Resultado = responseGuardarComentarioBlog.Result });
            }
            else
            {
                return Json(new { IsSuccess = false, Mensaje = responseGuardarComentarioBlog.Message });
            }
        }


        public async Task<IActionResult> TerminosyCondiciones()
        {
            //informacion de acceso ------------------------------
            var url = Constants.UrlAPI;
            var acceso = GetAccess.Instance(_apiService).GetToken();
            var _dataAccess = acceso.Result;

            //Informacion Blogs ------------------------------
            var responseBlog = await _apiService.GetBlogs(url, Constants.UrlAPP, "/api/Blog", _dataAccess.token_type, _dataAccess.access_token);
            if (responseBlog.Result != null && responseBlog.Result.blog.Count > 0)
            {

HotelCostaRicaCore/HotelCostaRicaCore.Web/Views/Nosotros/Blog.cshtml
            <!--  wrapper  -->
<div id="wrapper">
	<!-- content-->
	<div class="content">
		<!--  section  -->
		<section class="color-bg middle-padding ">
			<div class="wave-bg wave-bg2"></div>
			<div class="container">
				<div class="flat-title-wrap">
					<h2><span>Nuestras Noticias</span></h2>
					<span class="section-separator"></span>
					<h4>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Ut nec tincidunt arcu, sit amet fermentum sem.</h4>
				</div>
			</div>
		</section>
		<!--  section  end-->
		<div class="breadcrumbs-fs fl-wrap">
			<div class="container">
				<div class="breadcrumbs fl-wrap"><a href="#">Inicio</a><a href="#">Blog</a><span>Blog Clasico</span></div>
			</div>
		</div>
		<!-- section-->
		<section id="sec1" class="middle-padding grey-blue-bg">
			<div class="container">
				<div class="row">
					<!--blog content -->
					<div class="col-md-8">
						<!--post-container -->
						<div class="post-container fl-wrap articulosBlog">

							@foreach (var articulo in ViewBag.Blogs)
							{
								<!-- article> -->
								<article class="post-article">
									<div class="list-single-main-media fl-wrap">
										<img src="@articulo.ImageFullPath" class="respimg" alt="">
									</div>
									<div class="list-single-main-item fl-wrap">
										<div class="list-single-main-item-title fl-wrap">
											<h3><a href="/Nosotros/InternaBlog/@(articulo.idBlog)">@Html.Raw(articulo.Titulo)</a></h3>
										</div>
										<div class="contenidoBlog">
											@Html.Raw(articulo.Descripcion)
										</div>
										<div class="post-author"><a href="#"><img src="~/images/Banderas/costarica.png" alt=""><span>Por , @articulo.Usuario</span></a></div>
										<div class="post-opt">
											<ul>
												<li><i class="fal fa-calendar"></i> <span>@articulo.Fecha.ToString("dd MMMM yyyy") </span></li>
												<li><i class="fal fa-eye"></i> <span>@articulo.Vistas</span></li>
												<li>
													<i class="fal fa-tags"></i>
													<a href="#">Fotografía</a> , <a href="#">Diseño</a>
												</li>
											</ul>
										</div>
										<span class="fw-separator"></span>
										<div class="list-single-main-item-title fl-wrap">
											<h3>Tags</h3>
										</div>
										<div class="list-single-tags tags-stylwrap blog-tags">
											@if (articulo.ListTags != null && articulo.ListTags.Count > 0)
											{
												foreach (var Tag in articulo.ListTags)
												{
													<a href="#">@Tag</a>
												}
											}
										</div>
										<span class="fw-separator"></span>
										<a href="/Nosotros/InternaBlog/@(articulo.idBlog)" class="btn  float-btn color-bg">Leer más<i class="fal fa-angle-right"></i></a>
									</div>
								</article>
								<!-- article end -->

							}



							<!-- pagination-->
							<div class="pagination" id="pagination">
								<a href="#" class="prevposts-link"><i class="fa fa-caret-left"></i></a>
								<a href="#">1</a>
								<a href="#" class="current-page">2</a>
								<a href="#">3</a>
								<a href="#">4</a>
								<a href="#" class="nextposts-link"><i class="fa fa-caret-right"></i></a>
							</div>
							<!-- pagination end-->
						</div>
						<!--post-container end -->
					</div>
					<!-- blog content end -->
					<!--   sidebar  -->
					<div class="col-md-4">
						<!--box-widget-wrap -->
						<div class="box-widget-wrap fl-wrap fixed-bar">
							<!--box-widget-item -->
							<div class="box-widget-item fl-wrap">
								<div class="box-widget">
									<div class="box-widget-content">
										<div class="box-widget-item-header">
											<h3> Buscar en el Blog </h3>
										</div>
										<div class="search-widget">
											<form action="#" class="fl-wrap">
												<input name="se" id="se" type="text" class="search" placeholder="Buscar.." />
												<button class="search-submit color2-bg" id="submit_btn"><i class="fa fa-search transition"></i> </button>
											</form>
										</div>
									</div>
								</div>
							</div>
							<!--box-widget-item end -->
							<!--box-widget-item -->
							<div class="box-widget-item fl-wrap">
								<div class="box-widget counter-widget" data-countDate="09/12/2019">
									<div class="banner-wdget fl-wrap">
										@*<div class="overlay"></div>*@
										<div class="bg" data-bg="/images/bannercc.png"></div>
										<div class="banner-wdget-content fl-wrap" style="opacity:0; user-select:none">
											<h4>Get a discount <span>20%</span> when ordering a room from three days.</h4>
											<div class="countdown fl-wrap">
												<div class="countdown-item">
													<span class="days rot">00</span>
													<p>days</p>
												</div>
												<div class="countdown-item">
													<span class="hours rot">00</span>
													<p>hours </p>
												</div>
												<div class="countdown-item">
													<span class="minutes rot">00</span>
													<p>minutes </p>
												</div>
												<div class="countdown-item">
													<span class="seconds rot">00</span>
													<p>seconds</p>
												</div>
											</div>
											<a href="#">Book Now</a>
										</div>
									</div>
								</div>
							</div>
							<!--box-widget-item end -->
							<!--box-widget-item -->
							<div class="box-widget-item fl-wrap">
								<div class="box-widget widget-posts">
									<div class="box-widget-content MasArticulos">
										<div class="box-widget-item-header">
											<h3>Más Articulos</h3>
										</div>
										@foreach (var articuloSideBar in ViewBag.MasArticulos)
										{
											<!--box-image-widget-->
											<div class="box-image-widget">
												<div class="box-image-widget-media">
													<img src="@articuloSideBar.DirImage" alt="">
													<a href="/Nosotros/InternaBlog/@(articuloSideBar.idBlog)" class="color-bg">Leer</a>
												</div>
												<div class="box-image-widget-details">
													<h4>@Html.Raw(articuloSideBar.Titulo) </h4>
													<p class="multi-line-truncate contenidoArticulo">@Html.Raw(articuloSideBar.ContenidoHome)</p>
													<span class="widget-posts-date"><i class="fal fa-calendar"></i>@articuloSideBar.FechaArticulo</span>
												</div>
											</div>
											<!--box-image-widget end -->
										}
									</div>
								</div>
							</div>
							<!--box-widget-item end -->
							<!--box-widget-item -->
							<div class="box-widget-item fl-wrap">
								<div class="box-widget">
									<div class="box-widget-content">
										<div class="box-widget-item-header">
											<h3>Nuestro Instagram</h3>
										</div>
										<div class="jr-insta-thumb">
											<ul>
												<li>
													<a href="#"><img src="~/images/ximgHome/8-1.jpg" alt=""></a>
												</li>
												<li>
													<a href="#"><img src="~/images/ximgHome/8-2.jpg" alt=""></a>
												</li>
												<li>
													<a href="#"><img src="~/images/ximgHome/9.jpg" alt=""></a>
												</li>
												<li>
													<a href="#"><img src="~/images/ximgHome/2-3.jpg" alt=""></a>
												</li>
												<li>
													<a href="#"><img src="~/images/ximgHome/2-4.jpg" alt=""></a>
												</li>
												<li>
													<a href="#"><img src="~/images/ximgHome/2-5.jpg" alt=""></a>
												</li>
											</ul>
										</div>
									</div>
								</div>
							</div>
							<!--box-widget-item end -->
							<!--box-widget-item -->
							<div class="box-widget-item fl-wrap">
								<div class="box-widget">
									<div class="box-widget-content">
										<div class="box-widget-item-header">
											<h3> Categorias</h3>
										</div>
										<ul class="cat-item">
											<li><a href="#">Estandar</a> <span>3</span></li>
											<li><a href="#">Video</a> <span>6 </span></li>
											<li><a href="#">Galeria</a> <span>12 </span></li>
											<li><a href="#">Citas</a> <span>4</span></li>
										</ul>
									</div>
								</div>
							</div>
							<!--box-widget-item end -->
						</div>
						<!--box-widget-wrap end -->
					</div>
					<!--   sidebar end  -->
				</div>
			</div>
			<div class="limit-box fl-wrap"></div>
		</section>
		<!-- section end -->
	</div>
	<!-- content end-->
</div>
<!--wrapper end -->

<input type="hidden" id="totalblogs" name="totalblogs" value="@ViewBag.totalblogs" />
<input type="hidden" id="paginaActual" name="paginaActual" value="@ViewBag.NumPagina" />
<input type="hidden" id="blogsPorPagina" name="blogsPorPagina" value="@ViewBag.blogsPorPagina" />




@section Scripts{
<script>
	$(document).ready(function () {
		var totalblogs = $("#totalblogs").val();
		var NumPagina = $("#paginaActual").val();
		var blogsPorPagina = $("#blogsPorPagina").val();
		Paginacion(NumPagina, totalblogs, blogsPorPagina);
	});


	function Paginacion(NumPagina, totalblogs, blogsPorPagina) {
		var htmlPaginacion = "";


		//if (DataHoteles.length > 0) {
		if (totalblogs > 0) {

			var totalPaginas = Math.ceil(totalblogs / blogsPorPagina);

			if (NumPagina == 1) {
				htmlPaginacion = htmlPaginacion + "<a href='javascript:;' class='prevposts-link'><i class='fa fa-caret-left'></i></a>";
			}
			else {
				htmlPaginacion = htmlPaginacion + "<a href='/Nosotros/Blog/" + (NumPagina - 1)  + "' class='prevposts-link'><i class='fa fa-caret-left'></i></a>";
			}


			for (var i = 1; i <= totalPaginas; i++) {
				var PaginaActual = (i == NumPagina) ? "class='current-page'" : "";
				pag = "<a href='/Nosotros/Blog/" + i + "' " + PaginaActual +" >" + i + "</a>";
				htmlPaginacion = htmlPaginacion + pag;
			}

			if (NumPagina == totalPaginas) {
				htmlPaginacion = htmlPaginacion + "<a href='javascript:;' class='nextposts-link'><i class='fa fa-caret-right'></i></a>";
			}
			else {
				console.log(NumPagina);
				//htmlPaginacion = htmlPaginacion + "<a  onclick='MostrarHoteles(" + (NumPagina + 1) + ")'  class='nextposts-link'><i class='fa fa-caret-right'></i></a>";
				htmlPaginacion = htmlPaginacion + "<a  href='/Nosotros/Blog/" + (parseInt(NumPagina) + 1) +"'  class='nextposts-link'><i class='fa fa-caret-right'></i></a>";
			}

			$("#pagination").html(htmlPaginacion);

		}
		else {
			$("#pagination").html("");
		}

	}

</script>
}

HotelCostaRicaCore/HotelCostaRicaCore.Web/Views/Nosotros/Contacto.cshtml
<!--  wrapper  -->
<div id="wrapper">
	<!-- content-->
	<div class="content">
		<!-- map-view-wrap -->
		<div class="map-view-wrap">
			<div class="container">
				<div class="map-view-wrap_item">
					<div class="list-single-main-item-title fl-wrap">
						<h3>Contacto</h3>
					</div>
					<div class="box-widget-list mar-top">
						<ul>
							<li><span><i class="fal fa-map-marker"></i> Dirección :</span> <a href="#">San José, Pozos de Santa Ana</a></li>
							<li><span><i class="fal fa-phone"></i> Teléfono :</span> <a href="#">(506) 2203-0500</a></li>
							<li><span><i class="fal fa-envelope"></i> Email :</span> <a href="#">Soporte@costaricacheckin.com</a></li>
							<li><span><i class="fal fa-browser"></i> Website :</span> <a href="#">www.costaricacheckin.com</a></li>
						</ul>
					</div>
					<div class="list-widget-social">
						<ul>
							<li><a href="https://www.facebook.com/CostaRicaCheckIn/" target="_blank"><i class="fab fa-facebook-f"></i></a></li>
							<li><a href="https://www.instagram.com/costarica_checkin" target="_blank"><i class="fab fa-instagram"></i></a></li>
						</ul>
					</div>
				</div>
			</div>
		</div>
		<!--map-view-wrap end -->
		<!-- Map -->
		<div class="map-container fw-map2">
			<div id="singleMap" data-latitude="40.7427837" data-longitude="-73.11445617675781"></div>
		</div>
		<!-- Map end -->
		<div class="breadcrumbs-fs fl-wrap">
			<div class="container">
				<div class="breadcrumbs fl-wrap"><a href="#">Inicio</a><a href="#">Paginas</a><span>Contacto</span></div>
			</div>
		</div>
		<section id="sec1" class="grey-b lue-bg middle-padding">
			<div class="container">
				<div class="row">
					<div class="col-md-4">
						<!--   list-single-main-item -->
						<div class="list-single-main-item fl-wrap">
							<div class="list-single-main-item-title fl-wrap">
								<h3>Nosotros </h3>
							</div>
							<div class="list-single-main-media fl-wrap">
								<img src="~/images/xImg/FotoNosotros.png" alt="" class="respimg">
							</div>
							<p>En CostaRicacheckin.com nuestro objetivo es velar por el turismo local y mostrarle al mundo lo privilegiados que somos al nacer en un país que puede ser pequeño en extensión pero con grandes sorpresas en cada rincón. </p>
						</div>
						<!--   list-single-main-item end -->
					</div>
					<div class="col-md-8">
						<div class="list-single-main-item fl-wrap">
							<div class="list-single-main-item-title fl-wrap">
								<h3>Ponerse en contacto</h3>
							</div>
							<div id="contact-form">
								<div id="message"></div>
								<form class="custom-form" action="#" name="contactform" id="contactform">
									<fieldset>
										<label><i class="fal fa-user"></i></label>
										<input type="text" name="name" id="name" placeholder="Nombre *" value="" required/>
										<div class="clearfix"></div>
										<label><i class="fal fa-envelope"></i>  </label>
										<input type="text" name="email" id="email" placeholder="Correo Electronico*" value="" required/>

										<textarea name="comments" id="comments" cols="40" rows="3" placeholder="Mensaje:" required></textarea>
									</fieldset>
									<button class="btn float-btn color2-bg" style="margin-top:15px;" id="btnEnviarCorreo"  > Enviar Mensaje<i class="fal fa-angle-right"></i></button>
								</form>
							</div>
							<!-- contact form  end-->
						</div>
					</div>
				</div>
			</div>
			<div class="section-decor"></div>
		</section>
		<section class="section-publicidad">
			<div class="container">
				<img src="~/images/xImg/bannercclg.png" />
			</div>
		</section>
		<!-- section end -->
	</div>
	<!-- content end-->
</div>
<!--wrapper end -->


@section Scripts{	
	<partial name="_ValidationScriptsPartial" />
	<script>


		$("#btnEnviarCorreo").click(function (e)
		{

			e.preventDefault();
			if (!$('#contactform').valid()) {
                Swal.fire({
				    icon: 'warning',
                    text: 'Debe completar el formulario',
                    customClass: {
                        confirmButton: 'BtnMirarOpciones',
                    }
			    });
			    return false;
			}

            var data = {
                NomCliente: $("#name").val(),
                Email: $("#email").val(),
				Mensaje: $("#comments").val()
            };

            $.ajax({
                type: "POST",
                url: "@Url.Action("EnviarCorreo", "Nosotros")",
                data: { data: data },
				success: function (data) {
                    if (data.IsSuccess == true) {
                        Swal.fire({
                            icon: 'success',
                            title: '¡Completado!',
                            text: 'El mensaje fue enviado correctamente',
                            customClass: {
                                confirmButton: 'BtnMirarOpciones',
                            }
			            });
                        limpiarFormulario();
                    }
                    else {
                        Swal.fire({
                            icon: 'error',
                            title: '¡Error!',
                            text: 'No se pudo enviar el mensaje',
                            customClass: {
                                confirmButton: 'BtnMirarOpciones',
                            }
			            });
                    }
                },
                error: function () {
                    Swal.fire({
                        icon: 'error',
                        title: '¡Error!',
                        text: 'No se pudo enviar el mensaje',
                        customClass: {
                            confirmButton: 'BtnMirarOpciones',
                        }
			        });
				},
				beforeSend: function () {
                    Swal.fire({
	                     allowOutsideClick: false,
	                     showConfirmButton: false,
	                     showClass: {
		                    popup: 'animated fadeIn faster'
	                      },
	                     customClass: {
				                    container: 'sweetLoadingcontent'
			                      },
	                    html:"<div class='animacionJson'><lottie-player src='/js/LoadingcataratasGris.json' background='transparent' speed='1' style='width: 150px; height: 150px;' loop  autoplay>"+
		                    "</lottie-player></div>"
                    });
				}
            });

		});
				

		function limpiarFormulario() {
			$('#contactform')[0].reset();
		}
	</script>
}